# Generated by Django 5.0.4 on 2024-04-30 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_question_explanation_alter_question_question_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='text',
            new_name='question',
        ),
    ]
