# Generated by Django 5.0.4 on 2024-06-23 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='questions',
            field=models.ManyToManyField(blank=True, to='api.question'),
        ),
    ]
