# Generated by Django 5.0.4 on 2024-06-24 20:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_trakedquestion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TrakedQuestion',
            new_name='TrackedQuestion',
        ),
    ]
