# Generated by Django 5.0.4 on 2024-07-05 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_room_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('Searching', 'Searching'), ('Battling', 'Battling'), ('Ended', 'Ended')], max_length=10),
        ),
    ]
