# Generated by Django 5.0.4 on 2024-07-11 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_remove_question_winner_room_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='user1_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='room',
            name='user2_score',
            field=models.IntegerField(default=0),
        ),
    ]
