# Generated by Django 5.0.4 on 2024-07-19 14:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_tournament_tournamentparticipation_tournamentanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='description',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tournament',
            name='duration',
            field=models.DurationField(default=django.utils.timezone.timedelta(hours=24)),
            preserve_default=False,
        ),
    ]
