# Generated by Django 5.0.4 on 2024-07-19 15:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_tournament_description_tournament_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(days=1)),
        ),
    ]
