# Generated by Django 5.0.4 on 2024-07-31 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_profile_country_profile_elo_rating_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournamentanswer',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='tournamentanswer',
            name='is_correct',
        ),
        migrations.AddField(
            model_name='tournament',
            name='private',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tournamentanswer',
            name='status',
            field=models.CharField(choices=[('Correct', 'Correct'), ('Incorrect', 'Incorrect'), ('Blank', 'Blank')], default='Blank', max_length=10),
            preserve_default=False,
        ),
    ]
