# Generated by Django 5.0.4 on 2024-07-31 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_remove_tournamentanswer_answer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournamentparticipation',
            name='end_time',
        ),
    ]
