# Generated by Django 5.0.4 on 2024-07-31 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_remove_tournamentparticipation_end_time'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TournamentAnswer',
            new_name='TournamentQuestion',
        ),
    ]
