# Generated by Django 5.0.4 on 2024-07-31 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_profile_country_profile_elo_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournamentquestion',
            name='time_taken',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
