# Generated by Django 5.0.4 on 2024-07-31 21:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_alter_tournamentquestion_time_taken'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentparticipation',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(seconds=1800)),
        ),
    ]
