# Generated by Django 5.0.4 on 2024-07-31 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_tournamentparticipation_end_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournamentparticipation',
            name='score',
        ),
    ]
