# Generated by Django 5.0.4 on 2024-07-31 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_remove_tournamentparticipation_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentparticipation',
            name='last_correct_submission',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tournamentparticipation',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
