# Generated by Django 5.0.4 on 2024-08-01 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_tournamentparticipation_last_correct_submission_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournamentparticipation',
            name='last_correct_submission',
        ),
    ]
