# Generated by Django 5.0.4 on 2024-08-01 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_remove_tournamentparticipation_last_correct_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentparticipation',
            name='last_correct_submission',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
