# Generated by Django 5.0.4 on 2024-08-01 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_tournamentparticipation_last_correct_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentparticipation',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Completed', 'Completed')], default='Active', max_length=10),
            preserve_default=False,
        ),
    ]
