# Generated by Django 5.0.4 on 2024-08-13 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_tournamentparticipation_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('animation_data', models.JSONField()),
                ('coin_multipliers', models.JSONField(default=dict)),
            ],
        ),
        migrations.AddField(
            model_name='infinitequestionstatistics',
            name='coins',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='infinitequestionstatistics',
            name='level',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='infinitequestionstatistics',
            name='normal_multiplier',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='infinitequestionstatistics',
            name='xp',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='UserAlcumusProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xp', models.IntegerField(default=0)),
                ('level', models.IntegerField(default=0)),
                ('coins', models.IntegerField(default=0)),
                ('normal_multiplier', models.FloatField(default=1.0)),
                ('user_pet_levels', models.JSONField(default=dict)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='alcumus_profile', to='api.profile')),
            ],
        ),
        migrations.CreateModel(
            name='UserInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pets', models.ManyToManyField(blank=True, related_name='owners', to='api.pet')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_inventory', to='api.profile')),
            ],
        ),
    ]
