# Generated by Django 5.2.4 on 2026-07-04 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_profile_goal_profile_my_tournaments_profile_pets_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('Waiting', 'Waiting'), ('Battling', 'Battling'), ('Ended', 'Ended')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='question',
            name='difficulty',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], db_index=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(blank=True, db_index=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('Searching', 'Searching'), ('Battling', 'Battling'), ('Ended', 'Ended')], db_index=True, max_length=10),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['question_type', 'difficulty'], name='api_questio_questio_6debd5_idx'),
        ),
    ]
