# Generated by Django 5.2.4 on 2026-07-04 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_alter_game_status_alter_question_difficulty_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='user',
        ),
        migrations.DeleteModel(
            name='Area',
        ),
        migrations.DeleteModel(
            name='House',
        ),
    ]
