# Generated by Django 5.2.4 on 2026-07-06 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_profile_avatar_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userstatistics',
            name='level',
        ),
        migrations.RemoveField(
            model_name='userstatistics',
            name='xp',
        ),
    ]
