# Generated by Django 5.2.4 on 2026-07-06 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_remove_userstatistics_level_remove_userstatistics_xp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalizedquest',
            name='template',
        ),
        migrations.RemoveField(
            model_name='personalizedquest',
            name='user',
        ),
        migrations.AddField(
            model_name='profile',
            name='last_practice_completed',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='longest_practice_streak',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='practice_streak',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='QuestTemplate',
        ),
        migrations.DeleteModel(
            name='PersonalizedQuest',
        ),
    ]
