# Generated by Codex on 2026-07-07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_remove_personalizedquest_template_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='active_practice_question',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='+',
                to='api.question',
            ),
        ),
    ]
