# Generated by Django 5.2.4 on 2026-07-07 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_profile_active_practice_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='active_math_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='api.question'),
        ),
        migrations.AddField(
            model_name='profile',
            name='math_elo_rating',
            field=models.IntegerField(default=1200),
        ),
    ]
