# Generated by Django 5.2.4 on 2026-07-17 03:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0065_account_onboarding'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('english', 'English'), ('math', 'Math')], db_index=True, default='english', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='api.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_questions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['user', 'subject'], name='api_savedqu_user_id_8fab50_idx'), models.Index(fields=['user', 'created_at'], name='api_savedqu_user_id_f6e3d0_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'question'), name='unique_saved_question_per_user')],
            },
        ),
    ]
