# Generated by Django 5.2.4 on 2026-07-18 15:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0066_savedquestion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PartyRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=6)),
                ('status', models.CharField(choices=[('lobby', 'lobby'), ('countdown', 'countdown'), ('question', 'question'), ('leaderboard', 'leaderboard'), ('finished', 'finished')], default='lobby', max_length=12)),
                ('max_players', models.IntegerField(default=6)),
                ('num_questions', models.IntegerField(default=10)),
                ('seconds_per_question', models.IntegerField(default=90)),
                ('subject', models.CharField(choices=[('math', 'math'), ('english', 'english'), ('mixed', 'mixed')], default='mixed', max_length=8)),
                ('difficulty', models.CharField(choices=[('easy', 'easy'), ('medium', 'medium'), ('hard', 'hard')], default='medium', max_length=6)),
                ('question_ids', models.JSONField(default=list)),
                ('current_index', models.IntegerField(default=0)),
                ('phase_started_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosted_parties', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PartyPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('answers', models.JSONField(default=dict)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='api.partyroom')),
            ],
            options={
                'ordering': ['id'],
                'constraints': [models.UniqueConstraint(fields=('room', 'user'), name='unique_party_player')],
            },
        ),
    ]
