# Generated by Django 5.2.4 on 2026-07-18 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0067_partyroom_partyplayer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamequestion',
            name='game',
        ),
        migrations.RemoveField(
            model_name='gamequestion',
            name='user',
        ),
        migrations.DeleteModel(
            name='Game',
        ),
        migrations.DeleteModel(
            name='GameQuestion',
        ),
    ]
