# Generated by Django 5.2.4 on 2026-07-19 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0068_remove_gamequestion_game_remove_gamequestion_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partyplayer',
            name='team',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='partyroom',
            name='mode',
            field=models.CharField(choices=[('classic', 'classic'), ('teams', 'teams'), ('survival', 'survival'), ('jeopardy', 'jeopardy')], default='classic', max_length=10),
        ),
        migrations.AddField(
            model_name='partyroom',
            name='num_teams',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='partyroom',
            name='random_teams',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='partyroom',
            name='team_names',
            field=models.JSONField(default=list),
        ),
    ]
