# Generated by Django 5.2.4 on 2026-07-19 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0069_partyplayer_team_partyroom_mode_partyroom_num_teams_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partyplayer',
            name='wager',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='partyplayer',
            name='wager_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='partyroom',
            name='status',
            field=models.CharField(choices=[('lobby', 'lobby'), ('countdown', 'countdown'), ('question', 'question'), ('wager', 'wager'), ('leaderboard', 'leaderboard'), ('finished', 'finished')], default='lobby', max_length=12),
        ),
    ]
