# Generated by Django 5.2.4 on 2026-07-19 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0070_partyplayer_wager_partyplayer_wager_locked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partyplayer',
            name='lives',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='partyroom',
            name='last_standing',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='partyroom',
            name='lives',
            field=models.IntegerField(default=3),
        ),
    ]
