# Generated by Django 5.2.4 on 2026-07-20 21:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0072_goldrush'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PracticeTestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_id', models.IntegerField(default=1)),
                ('test_name', models.CharField(default='SAT Diagnostic Test', max_length=100)),
                ('score', models.IntegerField()),
                ('correct', models.IntegerField()),
                ('total', models.IntegerField()),
                ('time_used_seconds', models.IntegerField(blank=True, null=True)),
                ('questions', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_test_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='api_practic_user_id_070ab0_idx')],
            },
        ),
    ]
