# Generated by Django 5.2.4 on 2026-08-07 06:51

import api.models
from django.db import migrations, models


def normalize_existing_grades(apps, schema_editor):
    Profile = apps.get_model('api', 'Profile')
    PendingRegistration = apps.get_model('api', 'PendingRegistration')
    low_grades = ['<1', '1', '2', '3', '4', '5', '6', '7']
    Profile.objects.filter(grade__in=low_grades).update(grade='8')
    PendingRegistration.objects.filter(grade__in=low_grades).update(grade='8')


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0075_pendingregistration_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='grade_last_promoted_year',
            field=models.PositiveSmallIntegerField(default=api.models.current_school_year, help_text='September school-year start most recently applied to this grade.'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='grade',
            field=models.CharField(choices=[('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('>12', '>12')], default='11', max_length=3),
        ),
        migrations.RunPython(normalize_existing_grades, migrations.RunPython.noop),
    ]
