# Generated by Django 5.2.8 on 2026-08-08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0079_practicetestmodule'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PracticeTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_practice_tests', to=settings.AUTH_USER_MODEL)),
                ('english_a', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='practice_test_english_a', to='api.practicetestmodule')),
                ('english_b', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='practice_test_english_b', to='api.practicetestmodule')),
                ('english_c', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='practice_test_english_c', to='api.practicetestmodule')),
                ('math_a', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='practice_test_math_a', to='api.practicetestmodule')),
                ('math_b', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='practice_test_math_b', to='api.practicetestmodule')),
                ('math_c', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='practice_test_math_c', to='api.practicetestmodule')),
            ],
            options={'ordering': ['-created_at', '-id']},
        ),
        migrations.CreateModel(
            name='PracticeTestAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed')], db_index=True, default='active', max_length=12)),
                ('phase', models.CharField(default='english_a', max_length=20)),
                ('selected_routes', models.JSONField(default=dict)),
                ('answers', models.JSONField(default=dict)),
                ('review_questions', models.JSONField(default=dict)),
                ('remaining_seconds', models.JSONField(default=dict)),
                ('current_question', models.PositiveIntegerField(default=1)),
                ('reading_writing_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('math_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('total_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('score_details', models.JSONField(default=dict)),
                ('contributes_to_calibration', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('practice_test', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attempts', to='api.practicetest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adaptive_test_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [
                    models.Index(fields=['practice_test', 'status'], name='api_practic_practic_fb84f8_idx'),
                    models.Index(fields=['user', 'status', 'created_at'], name='api_practic_user_id_787ba2_idx'),
                ],
                'constraints': [
                    models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('user', 'practice_test'), name='one_active_attempt_per_user_test'),
                    models.UniqueConstraint(condition=models.Q(('contributes_to_calibration', True)), fields=('user', 'practice_test'), name='one_calibration_attempt_per_user_test'),
                ],
            },
        ),
    ]
