# Generated by Django 5.2.8 on 2026-08-09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0080_practicetest_practicetestattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='practicetest',
            name='test_type',
            field=models.CharField(
                choices=[
                    ('full', 'Full SAT'),
                    ('english', 'Reading and Writing only'),
                    ('math', 'Math only'),
                ],
                db_index=True,
                default='full',
                max_length=10,
            ),
        ),
        *[
            migrations.AlterField(
                model_name='practicetest',
                name=field,
                field=models.OneToOneField(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.PROTECT,
                    related_name=f'practice_test_{field}',
                    to='api.practicetestmodule',
                ),
            )
            for field in ('english_a', 'english_b', 'english_c', 'math_a', 'math_b', 'math_c')
        ],
    ]
