# Generated by Django 5.2.4 on 2026-08-11 01:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


TEST_PREPS = [
    ('sat', 'SAT', True, 1),
    ('act', 'ACT', False, 2),
    ('ssat', 'SSAT', False, 3),
    ('gre', 'GRE', False, 4),
]

TEST_SECTIONS = {
    'sat': [('english', 'Reading and Writing'), ('math', 'Math')],
    'act': [('english', 'English'), ('math', 'Math'), ('reading', 'Reading'), ('science', 'Science')],
    'ssat': [('verbal', 'Verbal'), ('quantitative', 'Quantitative'), ('reading', 'Reading'), ('writing', 'Writing Sample')],
    'gre': [('verbal', 'Verbal Reasoning'), ('quantitative', 'Quantitative Reasoning'), ('analytical-writing', 'Analytical Writing')],
}

MATH_QUESTION_TYPES = [
    'Linear equations in one variable', 'Linear functions', 'Linear equations in two variables',
    'Systems of two linear equations in two variables', 'Linear inequalities in one or two variables',
    'Equivalent expressions', 'Nonlinear equations in one variable and systems of equations in two variables',
    'Nonlinear functions', 'Ratios, rates, proportional relationships, and units', 'Percentages',
    'One-variable data: distributions and measures of center and spread',
    'Two-variable data: models and scatterplots', 'Probability and conditional probability',
    'Inference from sample statistics and margin of error',
    'Evaluating statistical claims: observational studies and experiments', 'Area and volume',
    'Lines, angles, and triangles', 'Right triangles and trigonometry', 'Circles',
]


def seed_test_preps(apps, schema_editor):
    TestPrep = apps.get_model('api', 'TestPrep')
    for code, name, active, display_order in TEST_PREPS:
        TestPrep.objects.update_or_create(
            code=code,
            defaults={'name': name, 'active': active, 'display_order': display_order},
        )


def backfill_multi_test_data(apps, schema_editor):
    TestSection = apps.get_model('api', 'TestSection')
    for test_prep_id, sections in TEST_SECTIONS.items():
        for display_order, (code, name) in enumerate(sections, start=1):
            TestSection.objects.update_or_create(
                test_prep_id=test_prep_id,
                code=code,
                defaults={'name': name, 'active': True, 'display_order': display_order},
            )

    Question = apps.get_model('api', 'Question')
    Question.objects.filter(question_type__in=MATH_QUESTION_TYPES).update(subject='math')

    PracticeTypeStats = apps.get_model('api', 'PracticeTypeStats')
    PracticeTypeStats.objects.filter(question_type__in=MATH_QUESTION_TYPES).update(subject='math')

    Profile = apps.get_model('api', 'Profile')
    TestPrepUserStats = apps.get_model('api', 'TestPrepUserStats')
    TestPrepUserStats.objects.bulk_create([
        TestPrepUserStats(
            user_id=profile.user_id,
            test_prep_id='sat',
            duel_elo=profile.elo_rating,
            max_streak=profile.max_streak,
            practice_streak=profile.practice_streak,
            longest_practice_streak=profile.longest_practice_streak,
            last_practice_completed=profile.last_practice_completed,
        )
        for profile in Profile.objects.all().iterator()
    ], ignore_conflicts=True)


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0083_practicetestattempt_annotations_and_break'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TestPrep',
            fields=[
                ('code', models.SlugField(max_length=32, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80, unique=True)),
                ('active', models.BooleanField(db_index=True, default=False)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TestPrepUserStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duel_elo', models.IntegerField(default=1500)),
                ('max_streak', models.IntegerField(default=0)),
                ('practice_streak', models.IntegerField(default=0)),
                ('longest_practice_streak', models.IntegerField(default=0)),
                ('last_practice_completed', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TestSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=32)),
                ('name', models.CharField(max_length=80)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['test_prep__display_order', 'display_order', 'name'],
            },
        ),
        migrations.RunPython(seed_test_preps, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='profile',
            name='pets',
        ),
        migrations.RemoveConstraint(
            model_name='practiceactivequestion',
            name='unique_active_question_per_lane',
        ),
        migrations.RemoveConstraint(
            model_name='practicestats',
            name='unique_practice_stats_per_subject',
        ),
        migrations.RemoveConstraint(
            model_name='practicetypestats',
            name='unique_practice_type_stats',
        ),
        migrations.RemoveIndex(
            model_name='practiceattempt',
            name='api_practic_user_id_91adbf_idx',
        ),
        migrations.RemoveIndex(
            model_name='question',
            name='api_questio_questio_6debd5_idx',
        ),
        migrations.RemoveField(
            model_name='userstatistics',
            name='user_pet_levels',
        ),
        migrations.AddField(
            model_name='practicetypestats',
            name='subject',
            field=models.CharField(default='english', max_length=32),
        ),
        migrations.AddField(
            model_name='question',
            name='subject',
            field=models.CharField(db_index=True, default='english', max_length=32),
        ),
        migrations.AlterField(
            model_name='partyroom',
            name='subject',
            field=models.CharField(default='mixed', max_length=32),
        ),
        migrations.AlterField(
            model_name='practiceattempt',
            name='subject',
            field=models.CharField(db_index=True, default='english', max_length=32),
        ),
        migrations.AlterField(
            model_name='practicestats',
            name='subject',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='ranking',
            name='rank',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='ranking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='savedquestion',
            name='subject',
            field=models.CharField(db_index=True, default='english', max_length=32),
        ),
        migrations.AddField(
            model_name='partyroom',
            name='test_prep',
            field=models.ForeignKey(default='sat', on_delete=django.db.models.deletion.PROTECT, related_name='party_rooms', to='api.testprep'),
        ),
        migrations.AddField(
            model_name='powersprintstatistics',
            name='test_prep',
            field=models.ForeignKey(default='sat', on_delete=django.db.models.deletion.CASCADE, related_name='power_sprint_stats', to='api.testprep'),
        ),
        migrations.AddField(
            model_name='practiceactivequestion',
            name='test_prep',
            field=models.ForeignKey(default='sat', on_delete=django.db.models.deletion.CASCADE, related_name='active_questions', to='api.testprep'),
        ),
        migrations.AddField(
            model_name='practiceattempt',
            name='test_prep',
            field=models.ForeignKey(default='sat', on_delete=django.db.models.deletion.CASCADE, related_name='practice_attempts', to='api.testprep'),
        ),
        migrations.AddField(
            model_name='practicestats',
            name='test_prep',
            field=models.ForeignKey(default='sat', on_delete=django.db.models.deletion.CASCADE, related_name='practice_stats', to='api.testprep'),
        ),
        migrations.AddField(
            model_name='practicetest',
            name='test_prep',
            field=models.ForeignKey(default='sat', on_delete=django.db.models.deletion.PROTECT, related_name='adaptive_tests', to='api.testprep'),
        ),
        migrations.AddField(
            model_name='practicetestmodule',
            name='test_prep',
            field=models.ForeignKey(default='sat', on_delete=django.db.models.deletion.PROTECT, related_name='adaptive_modules', to='api.testprep'),
        ),
        migrations.AddField(
            model_name='practicetestresult',
            name='test_prep',
            field=models.ForeignKey(default='sat', on_delete=django.db.models.deletion.PROTECT, related_name='legacy_test_results', to='api.testprep'),
        ),
        migrations.AddField(
            model_name='practicetypestats',
            name='test_prep',
            field=models.ForeignKey(default='sat', on_delete=django.db.models.deletion.CASCADE, related_name='practice_type_stats', to='api.testprep'),
        ),
        migrations.AddField(
            model_name='profile',
            name='active_test_prep',
            field=models.ForeignKey(default='sat', on_delete=django.db.models.deletion.PROTECT, related_name='active_profiles', to='api.testprep'),
        ),
        migrations.AddField(
            model_name='question',
            name='test_prep',
            field=models.ForeignKey(default='sat', on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='api.testprep'),
        ),
        migrations.AddField(
            model_name='ranking',
            name='test_prep',
            field=models.ForeignKey(default='sat', on_delete=django.db.models.deletion.CASCADE, related_name='rankings', to='api.testprep'),
        ),
        migrations.AddField(
            model_name='room',
            name='test_prep',
            field=models.ForeignKey(default='sat', on_delete=django.db.models.deletion.PROTECT, related_name='duel_rooms', to='api.testprep'),
        ),
        migrations.AddField(
            model_name='savedquestion',
            name='test_prep',
            field=models.ForeignKey(default='sat', on_delete=django.db.models.deletion.CASCADE, related_name='saved_questions', to='api.testprep'),
        ),
        migrations.AddField(
            model_name='survivalstatistics',
            name='test_prep',
            field=models.ForeignKey(default='sat', on_delete=django.db.models.deletion.CASCADE, related_name='survival_stats', to='api.testprep'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='test_prep',
            field=models.ForeignKey(default='sat', on_delete=django.db.models.deletion.PROTECT, related_name='tournaments', to='api.testprep'),
        ),
        migrations.AddIndex(
            model_name='practiceattempt',
            index=models.Index(fields=['user', 'test_prep', 'subject'], name='api_practic_user_id_edb1c5_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['test_prep', 'subject', 'question_type', 'difficulty'], name='api_questio_test_pr_76a4c0_idx'),
        ),
        migrations.AddConstraint(
            model_name='practiceactivequestion',
            constraint=models.UniqueConstraint(fields=('user', 'test_prep', 'lane'), name='unique_active_question_per_test_lane'),
        ),
        migrations.AddConstraint(
            model_name='practicestats',
            constraint=models.UniqueConstraint(fields=('user', 'test_prep', 'subject'), name='unique_practice_stats_per_test_subject'),
        ),
        migrations.AddConstraint(
            model_name='practicetypestats',
            constraint=models.UniqueConstraint(fields=('user', 'test_prep', 'subject', 'question_type'), name='unique_practice_type_stats_per_test'),
        ),
        migrations.AddConstraint(
            model_name='ranking',
            constraint=models.UniqueConstraint(fields=('user', 'test_prep'), name='unique_ranking_per_test_prep'),
        ),
        migrations.AddConstraint(
            model_name='ranking',
            constraint=models.UniqueConstraint(fields=('test_prep', 'rank'), name='unique_rank_within_test_prep'),
        ),
        migrations.AddField(
            model_name='testprepuserstats',
            name='test_prep',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_stats', to='api.testprep'),
        ),
        migrations.AddField(
            model_name='testprepuserstats',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_prep_stats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='testsection',
            name='test_prep',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='api.testprep'),
        ),
        migrations.RunPython(backfill_multi_test_data, migrations.RunPython.noop),
        migrations.DeleteModel(
            name='Pet',
        ),
        migrations.AddIndex(
            model_name='testprepuserstats',
            index=models.Index(fields=['test_prep', '-duel_elo'], name='api_testpre_test_pr_be444a_idx'),
        ),
        migrations.AddConstraint(
            model_name='testprepuserstats',
            constraint=models.UniqueConstraint(fields=('user', 'test_prep'), name='unique_user_stats_per_test_prep'),
        ),
        migrations.AddConstraint(
            model_name='testsection',
            constraint=models.UniqueConstraint(fields=('test_prep', 'code'), name='unique_section_per_test_prep'),
        ),
    ]
