# Generated by Django 5.2.4 on 2026-08-11 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0084_multi_test_prep_foundation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='source',
            field=models.CharField(choices=[('sat_question_bank', 'SAT Question Bank'), ('official_question_bank', 'Official Question Bank'), ('ai_generated', 'AI Generated'), ('other', 'Other')], db_index=True, default='other', max_length=32),
        ),
    ]
