# Generated by Django 5.2.4 on 2026-08-11 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0085_generic_question_source'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PowerSprintStatistics',
        ),
        migrations.DeleteModel(
            name='Ranking',
        ),
    ]
